### ISSUE TITLE
[NumericUI] Add team ability cooldown ui

### ISSUE THREAD

**Issue by danreeves** [danreeves/darktide-mods#28]
A purple bar like vt2? + numbers with same options as own ability cd (timer and percent)

**Comment by Omerside** [comment]
#35 - Please note there's currently a bug where the bar doesn't disappear when the player is dead. I couldn't figure out why it sticks around, if you could take a look that'd be great help. The code of interest is probably here:  https://github.com/danreeves/darktide-mods/pull/35/commits/0ae30f27b6cab57f7c3bf6af2ce401c67c07571d#diff-00c4f5a3ff2ae297fe8febf22c4c585087dbfc7aee89ed48bc03000b04f27e2aR298-R316
