### ISSUE TITLE
Thumbnail skins to improve load times for index

### ISSUE THREAD

**Issue by Xuerian** [danreeves/darktide-mods#34]
Imagemagick seems to be in use here: https://github.com/danreeves/darktide-mods/blob/5845bd9da0aaf133e3fa9debc243e37fb7580224/Exporter/tools/convert.sh#L10

magick has a quick -thumbnail option: https://imagemagick.org/script/command-line-options.php#thumbnail

**Comment by danreeves** [comment]
Images are now resized to be more efficient
